### PR TITLE
Created Responsive sign in page

### PR DESCRIPTION
**Pull request by arsalanhub**

### CODE REVIEW

**Comment by ketan-mehta1304** [comment]
hi arsalan 
see u have to write the scss in the assets scss folder
create new .scss file and write the scss code
see scss is not vey different from css learn from here https://sass-lang.com/documentation/style-rules

**Comment by arsalanhub** [comment]
Can I modify already written CSS in asset folder?

**Comment by ketan-mehta1304** [comment]
the code u write in scss in assets folder automatically change to css but not the css one change to scss
so u have to write any code but in scss not css

**Comment by ketan-mehta1304** [comment]
7454948175

**Comment by manav014** [comment]
@arsalanhub, i think this PR is to be closed now. 
@ketan-mehta1304  please close this PR

**Comment by ketan-mehta1304** [comment]
done

**Pull request closed without merging**
